#!/usr/bin/env node
// build-tokens.mjs — design/tokens.json (DTCG) → 3 artifacts in packages/tokens/
//   1. src/tokens.css         CSS variables (:root)
//   2. tailwind.preset.cjs    Tailwind theme.extend preset
//   3. src/index.ts           TypeScript const

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SRC = resolve(ROOT, "design/tokens.json");
const OUT_CSS = resolve(ROOT, "packages/tokens/src/tokens.css");
const OUT_TW = resolve(ROOT, "packages/tokens/tailwind.preset.cjs");
const OUT_TS = resolve(ROOT, "packages/tokens/src/index.ts");

const raw = JSON.parse(readFileSync(SRC, "utf8"));

// ── reference resolver — replaces "{a.b}" with the leaf $value, recursive ──
function getPath(obj, path) {
  return path.split(".").reduce((acc, k) => (acc == null ? acc : acc[k]), obj);
}
function resolveRefs(val) {
  if (typeof val === "string") {
    let out = val;
    let prev;
    let i = 0;
    while (out !== prev && i++ < 10) {
      prev = out;
      out = out.replace(/\{([^}]+)\}/g, (_, p) => {
        const node = getPath(raw, p);
        const v = node && typeof node === "object" && "$value" in node ? node.$value : node;
        return typeof v === "string" || typeof v === "number" ? String(v) : `{${p}}`;
      });
    }
    return out;
  }
  if (Array.isArray(val)) return val.map(resolveRefs);
  if (val && typeof val === "object") {
    const out = {};
    for (const k of Object.keys(val)) out[k] = resolveRefs(val[k]);
    return out;
  }
  return val;
}

// ── collect category leafs as { key: resolvedValue } ──
function leafs(category) {
  const node = raw[category];
  if (!node) return {};
  const out = {};
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith("$")) continue;
    if (v && typeof v === "object" && "$value" in v) {
      out[k] = resolveRefs(v.$value);
    }
  }
  return out;
}

const colors = leafs("color");
const sections = leafs("section");
const fontWeights = leafs("fontWeight");
const fontFamily = leafs("fontFamily");
const spacing = leafs("spacing");
const radius = leafs("radius");
const elevation = leafs("elevation");
const breakpoint = leafs("breakpoint");

// typography is composite — keep object shape
function typo(category) {
  const node = raw[category];
  if (!node) return {};
  const out = {};
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith("$")) continue;
    if (v && typeof v === "object" && "$value" in v) out[k] = resolveRefs(v.$value);
  }
  return out;
}
const typography = typo("typography");
const typographyEn = typo("typographyEn");

// ────────────────────────────────────────────────────────
// 1. CSS variables
// ────────────────────────────────────────────────────────
const cssLines = [];
cssLines.push("/* generated by scripts/build-tokens.mjs — do not edit */");
cssLines.push(":root {");
for (const [k, v] of Object.entries(colors)) cssLines.push(`  --color-${k}: ${v};`);
for (const [k, v] of Object.entries(sections)) cssLines.push(`  --section-${k}: ${v};`);
for (const [k, v] of Object.entries(spacing)) cssLines.push(`  --space-${k}: ${v};`);
for (const [k, v] of Object.entries(radius)) cssLines.push(`  --radius-${k}: ${v};`);
for (const [k, v] of Object.entries(elevation)) cssLines.push(`  --shadow-${k}: ${v};`);
for (const [k, v] of Object.entries(breakpoint)) cssLines.push(`  --bp-${k}: ${v};`);
cssLines.push(`  --font-kr: ${fontFamily.kr.map((f) => (f.includes(" ") ? `'${f}'` : f)).join(", ")};`);
cssLines.push(`  --font-en: ${fontFamily.en.map((f) => (f.includes(" ") ? `'${f}'` : f)).join(", ")};`);
cssLines.push("}");

// utility classes for typography (so consumers can use `class="ds-h1"` without Tailwind)
cssLines.push("");
cssLines.push("/* typography utility classes (ko default) */");
for (const [k, v] of Object.entries(typography)) {
  cssLines.push(`.ds-${k} {`);
  cssLines.push(`  font-family: var(--font-kr);`);
  cssLines.push(`  font-size: ${v.fontSize};`);
  cssLines.push(`  font-weight: ${v.fontWeight};`);
  cssLines.push(`  line-height: ${v.lineHeight};`);
  cssLines.push(`  letter-spacing: ${v.letterSpacing};`);
  cssLines.push(`}`);
}
cssLines.push("");
cssLines.push("/* english variant */");
for (const [k, v] of Object.entries(typographyEn)) {
  cssLines.push(`:lang(en) .ds-${k}, .ds-${k}:lang(en) {`);
  cssLines.push(`  font-family: var(--font-en);`);
  cssLines.push(`  font-size: ${v.fontSize};`);
  cssLines.push(`  font-weight: ${v.fontWeight};`);
  cssLines.push(`  line-height: ${v.lineHeight};`);
  cssLines.push(`  letter-spacing: ${v.letterSpacing};`);
  cssLines.push(`}`);
}

mkdirSync(dirname(OUT_CSS), { recursive: true });
writeFileSync(OUT_CSS, cssLines.join("\n") + "\n");

// ────────────────────────────────────────────────────────
// 2. Tailwind preset
// ────────────────────────────────────────────────────────
const twFontSize = {};
for (const [k, v] of Object.entries(typography)) {
  twFontSize[k] = [
    v.fontSize,
    {
      lineHeight: v.lineHeight,
      letterSpacing: v.letterSpacing,
      fontWeight: String(v.fontWeight),
    },
  ];
}

const tw = {
  theme: {
    extend: {
      colors: { ...colors },
      spacing: { ...spacing },
      borderRadius: { ...radius },
      boxShadow: { ...elevation },
      fontFamily: {
        kr: fontFamily.kr,
        en: fontFamily.en,
        sans: fontFamily.kr,
      },
      fontSize: twFontSize,
      fontWeight: { ...fontWeights },
      screens: { ...breakpoint },
    },
  },
};

mkdirSync(dirname(OUT_TW), { recursive: true });
writeFileSync(
  OUT_TW,
  "// generated by scripts/build-tokens.mjs — do not edit\n" +
    "module.exports = " +
    JSON.stringify(tw, null, 2) +
    ";\n"
);

// ────────────────────────────────────────────────────────
// 3. TypeScript const
// ────────────────────────────────────────────────────────
const tsLines = [];
tsLines.push("// generated by scripts/build-tokens.mjs — do not edit");
tsLines.push("export const tokens = " + JSON.stringify({
  color: colors,
  section: sections,
  fontFamily,
  fontWeight: fontWeights,
  typography,
  typographyEn,
  spacing,
  radius,
  elevation,
  breakpoint,
}, null, 2) + " as const;");
tsLines.push("export type Tokens = typeof tokens;");
tsLines.push("export default tokens;");

mkdirSync(dirname(OUT_TS), { recursive: true });
writeFileSync(OUT_TS, tsLines.join("\n") + "\n");

console.log("✓ tokens.css       →", OUT_CSS);
console.log("✓ tailwind.preset  →", OUT_TW);
console.log("✓ index.ts         →", OUT_TS);
console.log(
  `  ${Object.keys(colors).length} colors · ${Object.keys(spacing).length} spacing · ` +
    `${Object.keys(radius).length} radii · ${Object.keys(typography).length} typo · ` +
    `${Object.keys(elevation).length} shadows`
);
